"""The small external contracts used by Knowli services."""

from typing import Protocol

from .claim import ClaimDraft
from .conflict import ConflictResolution


class Model(Protocol):
    def extract_claims(self, raw_text: str) -> list[ClaimDraft]: ...

    def find_conflicts(self, claims: list[ClaimDraft], candidates: list[dict]) -> list[dict]: ...

    def answer(self, question: str, claims: list[dict]) -> str: ...


class Embedder(Protocol):
    def embed(self, texts: list[str]) -> list[list[float]]: ...


class ContributionStore(Protocol):
    def create_contribution(self, user_id: str, raw_text: str, source: str, interview_id: str | None = None) -> dict: ...

    def get_contribution(self, user_id: str, contribution_id: str) -> dict | None: ...

    def save_review(self, user_id: str, contribution_id: str, revision: int, claims: list[ClaimDraft], resolutions: list[ConflictResolution]) -> dict: ...

    def commit_claims(self, user_id: str, contribution_id: str, revision: int) -> dict: ...

    def search_claims(self, query: str, embedding: list[float], limit: int) -> list[dict]: ...

    def list_history(self, cursor: str | None, limit: int) -> tuple[list[dict], str | None]: ...

    def create_interview(self, requester_id: str, assignee_id: str, title: str, brief: str | None = None) -> dict: ...

    def list_interviews(self, user_id: str, view: str) -> list[dict]: ...

    def start_interview(self, user_id: str, interview_id: str) -> dict: ...


class SessionStore(Protocol):
    def create_user(self, email: str, display_name: str, password_hash: str) -> dict: ...

    def get_user_by_email(self, email: str) -> dict | None: ...

    def create_session(self, user_id: str, token_hash: str, expires_at: str) -> None: ...

    def get_user_by_session(self, token_hash: str) -> dict | None: ...

    def delete_session(self, token_hash: str) -> None: ...
